### ISSUE TITLE
Merged Cells Causing Issues

### ISSUE THREAD

**Issue by ryanwoconnor** [ryanwoconnor/SheetsAddonforSplunk#1]
When cells are merged in a Google Sheet, we currently are unable to display them properly using Splunk. This needs to be addressed at some point (if possible). The current fix is to just not merge cells, but that may not always work for everyone.

**Comment by hobbes3** [comment]
I'll say the easiest solution is to repeat the values to all cells that are merged. Right now it just totally breaks if the app sees any merged cells, so that's unacceptable.

**Comment by ryanwoconnor** [comment]
I have a lead on getting this working. I was able to successfully parse a Google Sheet with merged cells using this method outside of Splunk fairly easily: https://johnricco.github.io/2017/04/04/python-html/

The big requirements this method has is pandas and html5lib. Python for Scientific Computing has pandas, but not html5lib. I'm going to talk with the Machine Learning team to see if we can get it added, and then I should be able to write a custom command to move us past this. 

https://splunkbase.splunk.com/app/2882/

**Comment by ryanwoconnor** [comment]
I managed to install these packages directly into Python for Scientific Computing last night using pip install html5lib -t <path_to_SA>

I was then able to utilize the package. Note: This method will not withstand upgrades but it is a workaround for the time being. We also have a project in place to hopefully add in an easier method to get these packages in place in the SA. For the time being this will work and will need to be part of setup instructions. I should now be able to keep moving on cooking up a way to visualize the merged cells and will keep you posted.

**Comment by ryanwoconnor** [comment]
Very close on this one, see the htmlsheet_export branch. The last step is that I need to get my Splunk account access to commit to the https://github.com/splunk/mltk-algo-contrib Git Repository. Once this is done, I wrote a fit algorithm to parse through HTML Tables using pandas and take care of merging cells. I'm sure we'll still find some edge cases, but we'll be much better positioned to handling them using Pandas as opposed to plain JSON.

**Comment by ryanwoconnor** [comment]
@hobbes3 There should be support for this now. This will need to be tested in the wild of course, but I am able to import a table with merged cells in my test environment now. See attached screenshots. 

<img width="1625" alt="screen shot 2019-01-08 at 2 35 28 pm" src="https://user-images.githubusercontent.com/11879871/50854303-aea7f680-1352-11e9-96d5-46bea44195fc.png">
<img width="918" alt="screen shot 2019-01-08 at 2 35 18 pm" src="https://user-images.githubusercontent.com/11879871/50854304-aea7f680-1352-11e9-9260-03e65748cb64.png">
