### ISSUE TITLE
Restriction on what sheets the app can see/pull

### ISSUE THREAD

**Issue by hobbes3** [ryanwoconnor/SheetsAddonforSplunk#5]
We need a way to restrict the app from pulling only certain subset of Google Sheets. Permissions is obviously a very important aspect of any organization. We wouldn't want people being able to pull financial or HR records when they only need to see a project list from the same Google account.

Here are my ideas:

1. Having the ability to restrict based on directories. For example, a configured account can only see sheets from the shared/ directory and nowhere else.
2. Permissions are set on the Google Drive side. By default the app can't see any sheets. Users in Google Drive give permission to the app, but right clicking a directory or sheet and choosing "Share". Then they enter the email address of the app (somehow) and the app can see once that email has read permission.

I prefer number 2, but not sure if it's possible or you'll have to completely rewrite the app with some kind of SMTP server or something lol. I'm not even sure if number 1 is possible since it sounds like the Google API allows _complete_ access to all files, which sounds very dangerous.

**Comment by hobbes3** [comment]
Here is more realistic use case:

Multiple NGOs share their sensitive documents to my Splunk's Google Drive account. Without some kind of permission restriction, one NGO can write a query to see other NGO's documents (and all other documents on my Drive). That's a big no-no from a privacy and security standpoint from both the NGO's and Splunk's perspective.

**Comment by ryanwoconnor** [comment]
I agree, I'm not completely sure on if either is possible lol I'm going to
read up on some of their docs though and see what I can come up with! Seems
like permissions are probably the biggest limitation at this point so let's
see if I can make some progress on that today!


Ryan O'Connor

**Comment by ryanwoconnor** [comment]
I sent a video in Slack today. I think there's two things here:

1. If multiple organizations are sharing documents with you, then you'll have the ability to see their documents. You definitely wouldn't want to authorize the Google Drive Add-on on their Splunk with your account. You'll only want to authorize the Google Drive Add-on with your account on a private Splunk instance (i.e. on your local machine). 

2. I think we can accomplish the second idea you had if we have the organization setup a shared Google Account. A lot of non-profits I've worked for actually have one already (I can think of at least 3 off the top of my head). If we do that, we can have the Google Drive Add-on for Splunk authorize as that account on the NGO's Splunk instance and Splunk will have Read-Only Access to the shared Google Account's Google Drive. A user can then continue to create documents in their own personal account without Splunk seeing the document. If they want Splunk to be able to read the document they created in their personal account, they can share it with the shared Google Account. I'll include a diagram of what that looks like here. 

<img width="900" alt="screen shot 2018-11-16 at 10 26 21 am" src="https://user-images.githubusercontent.com/11879871/48630373-20367a80-e98a-11e8-95ba-09e9f943cf89.png">

3. Lastly, how many organizations do you work with that are using G Suite Enterprise, Business, or Education editions? I think Team Drive support will be useful for a lot of organizations, but maybe not a lot of non-profits.

**Comment by ryanwoconnor** [comment]
Talked with @hobbes3 about this one today. Seems like we came to this as a resolution for the time being for non-profits without Team Drive. 

1. They will want to create a specific account to be used with Splunk. Then they can choose which documents to share with that account and subsequently limit what Splunk can see. 
2. If anyone else wants to edit a document, then that non-profit can share the document with that person's private account to be able to modify the document. 

I will open up a new ticket to build in Team Drive support down the road as that will be needed for enterprise users.
